tensorflow/quantum

scripts/test_tutorials.py

Temporary workaround, until we can figure out how to speed up the mnist notebook a little bit :)

Disable slow notebook test.

---

docs/_index.yaml

Add links to landing page

---

docs/tutorials/mnist.ipynb
scripts/test_tutorials.py

In `test_tutorials` script replace `NUM_EXAMPLES=.*`  with `NUM_EXAMPELS=10`.
Also: un-comment the line that actually runs the "remove_contradicting" function.

Reduce mnist num_examples when testing.

---

tensorflow_quantum/core/qsim/BUILD
tensorflow_quantum/core/qsim/state_space.cc
tensorflow_quantum/core/qsim/state_space.h
tensorflow_quantum/core/qsim/state_space_test.cc
tensorflow_quantum/core/qsim/util.cc
tensorflow_quantum/core/qsim/util.h

Moved sampling out of util into state_space.
This PR also adds `state_space_test` which will make it easier for us to start tackling #55 .

Move sample

---

tensorflow_quantum/core/src/circuit_parser.cc
tensorflow_quantum/core/src/circuit_parser.h
tensorflow_quantum/core/src/circuit_parser_test.cc

Added ability to take pauliTerm proto object and generate circuit object that takes you to the Z basis.
For Z you do nothing
For X you do Y ** -0.5
For Y you do X ** 0.5
This brings us one step closer to getting #144 .

Added z basis transformation to circuit_parser.

---

tensorflow_quantum/python/layers/circuit_executors/expectation.py
tensorflow_quantum/python/layers/circuit_executors/sampled_expectation.py
tensorflow_quantum/python/layers/high_level/controlled_pqc.py
tensorflow_quantum/python/layers/high_level/pqc.py

Using len on tensors isn't ideal we really ought to be using .shape, so made the changes where we needed.

Modified layers to use .shape instead of len when dealing with Tensors.

---

tensorflow_quantum/python/layers/high_level/controlled_pqc.py
tensorflow_quantum/python/layers/high_level/controlled_pqc_test.py
tensorflow_quantum/python/layers/high_level/pqc.py
tensorflow_quantum/python/layers/high_level/pqc_test.py

Added a `symbols` property to the high level layers so that if users want to extract the values from the weight tensors they can use `symbols` to cross reference to existing symbols without having to do the sorting themselves.

Added symbol properties to high level layers.

---

tensorflow_quantum/python/layers/high_level/pqc.py
tensorflow_quantum/python/layers/high_level/pqc_test.py

Added Symbol values function to PQC

---

tensorflow_quantum/core/qsim/state_space_avx.cc
tensorflow_quantum/core/qsim/state_space_sse.cc

Cut down the number of load instructions by 2x and also simplified some of the logic inside. Having those extra load instructions was also causing us to go OOB by 8 bytes on the last iteration of the loop.

Cleaned up SSE expectation.

---

tensorflow_quantum/core/ops/tfq_simulate_expectation_op.cc
tensorflow_quantum/core/ops/tfq_simulate_state_op.cc
tensorflow_quantum/core/qsim/BUILD
tensorflow_quantum/core/qsim/mux.cc
tensorflow_quantum/core/qsim/mux.h
tensorflow_quantum/core/qsim/mux_test.cc
tensorflow_quantum/core/qsim/state_space.h
tensorflow_quantum/core/qsim/state_space_avx.cc
tensorflow_quantum/core/qsim/state_space_avx.h
tensorflow_quantum/core/qsim/state_space_slow.cc
tensorflow_quantum/core/qsim/state_space_slow.h
tensorflow_quantum/core/qsim/state_space_sse.cc
tensorflow_quantum/core/qsim/state_space_sse.h
tensorflow_quantum/core/qsim/state_space_test.cc

General cleanup of some of the C++ code. Moved smart pointers into the return type for the Clone functions and the GetStateSpace function. Also added virtual tags and corrected typos on some functions.

Cleaned up smart poiner usage.

---

tensorflow_quantum/python/differentiators/parameter_shift.py

Fixed formatting causing autograph problem.

---

docs/install.md

Added python version support.

---

release/BUILD
scripts/import_test.py
tensorflow_quantum/__init__.py
tensorflow_quantum/core/__init__.py
tensorflow_quantum/core/ops/BUILD
tensorflow_quantum/core/ops/__init__.py
tensorflow_quantum/core/ops/tfq_calculate_unitary_op.cc
tensorflow_quantum/core/ops/tfq_simulate_ops_test.py
tensorflow_quantum/core/ops/tfq_unitary_op.py
tensorflow_quantum/core/ops/tfq_unitary_op_test.py
tensorflow_quantum/core/ops/tfq_utility_ops.py

Adds the `tfq.calculate_unitary` op.

Added tfq.calculate_unitary op.

---

tensorflow_quantum/core/ops/tfq_calculate_unitary_op.cc

Fast fix for https://github.com/tensorflow/quantum/issues/217

Change size_t to ptrdiff_t

---

tensorflow_quantum/core/ops/circuit_execution_ops_test.py
tensorflow_quantum/core/src/gates_def.cc
tensorflow_quantum/core/src/program_resolution.cc
tensorflow_quantum/core/src/program_resolution_test.cc

Precision fix

---

release/BUILD
tensorflow_quantum/core/ops/tfq_calculate_unitary_op.cc
tensorflow_quantum/python/layers/__init__.py
tensorflow_quantum/python/layers/circuit_executors/BUILD
tensorflow_quantum/python/layers/circuit_executors/__init__.py
tensorflow_quantum/python/layers/circuit_executors/unitary.py
tensorflow_quantum/python/layers/circuit_executors/unitary_test.py

Added the unitary layer to sit on top of the unitary op and provide some nice abstractions.

Added Unitary Layer.

---

docs/install.md
docs/tutorials/barren_plateaus.ipynb
docs/tutorials/gradients.ipynb
docs/tutorials/hello_many_worlds.ipynb
docs/tutorials/mnist.ipynb
docs/tutorials/qcnn.ipynb

Going to cut 0.3 right after which will auto install cirq 0.8 now

Prepare for 0.3.

---

tensorflow_quantum/python/util.py
tensorflow_quantum/python/util_test.py

Resolves #244.  Also made input tests more systematic.

Exponential error patch

---

release/setup.py
requirements.txt
tensorflow_quantum/core/ops/tfq_ps_util_ops_test.py
tensorflow_quantum/core/serialize/serializer_test.py

Upgrade sympy to 1.5

---

tensorflow_quantum/core/ops/tfq_calculate_unitary_op.cc
tensorflow_quantum/core/ops/tfq_simulate_expectation_op.cc
tensorflow_quantum/core/ops/tfq_simulate_sampled_expectation_op.cc
tensorflow_quantum/core/ops/tfq_simulate_state_op.cc
tensorflow_quantum/core/qsim/fuser_basic.cc
tensorflow_quantum/core/qsim/fuser_basic.h
tensorflow_quantum/core/qsim/fuser_basic_test.cc
tensorflow_quantum/core/qsim/mux.cc
tensorflow_quantum/core/qsim/mux.h
tensorflow_quantum/core/qsim/mux_test.cc
tensorflow_quantum/core/qsim/state_space.cc
tensorflow_quantum/core/qsim/state_space.h
tensorflow_quantum/core/qsim/state_space_avx.cc
tensorflow_quantum/core/qsim/state_space_avx.h
tensorflow_quantum/core/qsim/state_space_slow.cc
tensorflow_quantum/core/qsim/state_space_slow.h
tensorflow_quantum/core/qsim/state_space_sse.cc
tensorflow_quantum/core/qsim/state_space_sse.h
tensorflow_quantum/core/qsim/state_space_test.cc
tensorflow_quantum/core/qsim/unitary_space.cc
tensorflow_quantum/core/qsim/unitary_space.h
tensorflow_quantum/core/qsim/unitary_space_slow.cc
tensorflow_quantum/core/qsim/unitary_space_slow.h
tensorflow_quantum/core/qsim/unitary_space_test.cc
tensorflow_quantum/core/qsim/util.cc
tensorflow_quantum/core/qsim/util.h
tensorflow_quantum/core/qsim/util_test.cc

Rename qsim -> qsim_old.

---

WORKSPACE
tensorflow_quantum/core/src/BUILD
tensorflow_quantum/core/src/circuit_parser_qsim.cc
tensorflow_quantum/core/src/circuit_parser_qsim.h
tensorflow_quantum/core/src/circuit_parser_qsim_test.cc
tensorflow_quantum/core/src/gates_def.cc

Adds item 2 from #263.
Sorry for the size of this PR. It is very self contained and doesn't touch a lot of code.
Adds a parser for converting from our proto representation into the qsim format used here: https://github.com/quantumlib/qsim/blob/master/

Added Proto -> OSS qsim converter.

---

tensorflow_quantum/core/src/BUILD
tensorflow_quantum/core/src/circuit_parser_qsim.cc
tensorflow_quantum/core/src/circuit_parser_qsim.h
tensorflow_quantum/core/src/circuit_parser_qsim_test.cc

Adapted Pauli parsing from the existing `circuit_parser` to the new `circuit_parser_qsim`.

Add pauli parsing for new qsim.

---

tensorflow_quantum/core/ops/parse_context.cc
tensorflow_quantum/core/ops/parse_context.h

Removed some unused code from op dir.

Removed dead code.

---

tensorflow_quantum/core/serialize/serializer.py
tensorflow_quantum/core/serialize/serializer_test.py

This PR fixes precision issue during serialization & deserialization.

Deserializer rounding

---

tensorflow_quantum/core/src/util_qsim.h

Followed up from issue https://github.com/quantumlib/qsim/issues/147

Updated simulation work estimates

---

tensorflow_quantum/core/src/util_qsim.h
tensorflow_quantum/core/src/util_qsim_test.cc

Review after #300. Yet more work slowly porting over in #263. This copies over our SampledExpectation logic to be compatible with OSS qsim.

Compute sampled

---

tensorflow_quantum/core/ops/tfq_simulate_sampled_expectation_op.cc

We are very close to being done with the OSS qsim changeover and #263. All that is left is to move the unitary calculation features upstream to qsim and then the fun part...... removing the old qsim code :)

Moved Sampled Expectation op to OSS qsim.

---

tensorflow_quantum/core/ops/tfq_simulate_expectation_op.cc

Expectation parallelization.

---

tensorflow_quantum/core/ops/tfq_simulate_sampled_expectation_op.cc

Added parallel parsing to sampled expectation op.

Parallel upgrade for sampled expectation.

---

tensorflow_quantum/core/ops/BUILD
tensorflow_quantum/core/ops/parse_context.cc
tensorflow_quantum/core/ops/parse_context.h
tensorflow_quantum/core/ops/tfq_simulate_ops.py
tensorflow_quantum/core/ops/tfq_simulate_ops_test.py
tensorflow_quantum/core/ops/tfq_simulate_samples_op.cc
tensorflow_quantum/python/layers/circuit_executors/sample_test.py

Added a new op to improve sampling performance.

Better sampling op.

---

tensorflow_quantum/core/ops/tfq_simulate_samples_op.cc

Windws nightly builds are still failing. They are complaining about template resolution problems here. Hoping that this solves the issue.

Removed some templates in tfq_simulate_samples.cc

---

tensorflow_quantum/core/ops/tfq_simulate_samples_op.cc

Yet another fix attempt for windows builds.

More windows fix attempts.

---

scripts/import_test.py
tensorflow_quantum/__init__.py
tensorflow_quantum/core/__init__.py
tensorflow_quantum/core/ops/BUILD
tensorflow_quantum/core/ops/__init__.py
tensorflow_quantum/core/ops/tfq_calculate_unitary_op.cc
tensorflow_quantum/core/ops/tfq_resolve_parameters_op.cc
tensorflow_quantum/core/ops/tfq_utility_ops.py
tensorflow_quantum/core/ops/tfq_utility_ops_test.py
tensorflow_quantum/core/src/program_resolution.cc
tensorflow_quantum/core/src/program_resolution.h
tensorflow_quantum/core/src/program_resolution_test.cc
tensorflow_quantum/python/util.py
tensorflow_quantum/python/util_test.py

Adds the op called for in #286 for resolving parameters in-graph in circuits

Circuit parameter filler

---

WORKSPACE
tensorflow_quantum/core/src/circuit_parser_qsim.cc
tensorflow_quantum/core/src/util_qsim_test.cc

These qsim upgrades let us move forward with #263 and #256 .

Upgrade to qsim 0.3.0.

---

tensorflow_quantum/core/ops/batch_util.py
tensorflow_quantum/core/ops/batch_util_test.py
tensorflow_quantum/core/ops/circuit_execution_ops.py
tensorflow_quantum/core/ops/cirq_ops.py
tensorflow_quantum/core/ops/cirq_ops_test.py
tensorflow_quantum/python/layers/circuit_executors/sample.py

Resolves #315.  Enables general `cirq.Sampler`s to be used with Sample op and layer

Batch sample fix

---

WORKSPACE

Fix Eigen3 download.

---

release/setup.py
requirements.txt
scripts/build_pip_package_test.sh

Bump Cirq to 0.8.2.

---

scripts/import_test.py
tensorflow_quantum/__init__.py
tensorflow_quantum/core/__init__.py
tensorflow_quantum/core/ops/BUILD
tensorflow_quantum/core/ops/__init__.py
tensorflow_quantum/core/ops/tfq_unitary_op.py
tensorflow_quantum/core/ops/tfq_unitary_op_test.py
tensorflow_quantum/python/layers/circuit_executors/unitary.py

Added locking ability to unitary op.

---

tensorflow_quantum/python/differentiators/gradient_test.py

Currently we don't have a great set of tests, making sure that sampled differentiators are working correctly. Added tests here for `sampled_op` behavior.
I think we should try and get this in before #345 so that we can feel a little more confident about those bigger changes coming in.

Expanded differentiator tests.

---

tensorflow_quantum/core/ops/tfq_adj_grad_op.cc
tensorflow_quantum/core/ops/tfq_calculate_unitary_op.cc
tensorflow_quantum/core/ops/tfq_resolve_parameters_op.cc
tensorflow_quantum/core/ops/tfq_simulate_expectation_op.cc
tensorflow_quantum/core/ops/tfq_simulate_sampled_expectation_op.cc
tensorflow_quantum/core/ops/tfq_simulate_samples_op.cc
tensorflow_quantum/core/ops/tfq_simulate_state_op.cc

"Smart" pointers....
Fixes #383

Fixed qsim memory freeing issue.

---

docs/_book.yaml

I'm moving some of the generated files, and need to update the _book.yaml to match.

Update book for api gen changes (cl/331666270)

---

tensorflow_quantum/core/ops/parse_context.cc
tensorflow_quantum/core/ops/tfq_adj_grad_op.cc
tensorflow_quantum/core/ops/tfq_simulate_expectation_op.cc
tensorflow_quantum/core/ops/tfq_simulate_ops_test.py
tensorflow_quantum/core/ops/tfq_simulate_sampled_expectation_op.cc
tensorflow_quantum/python/layers/circuit_executors/expectation_test.py
tensorflow_quantum/python/layers/circuit_executors/sample_test.py
tensorflow_quantum/python/layers/circuit_executors/sampled_expectation_test.py
tensorflow_quantum/python/layers/circuit_executors/state_test.py
tensorflow_quantum/python/layers/circuit_executors/unitary_test.py

Fix certain invalid inputs causing segfault on expectation ops.

---

tensorflow_quantum/core/ops/math_ops/inner_product_op.py

Accidentally merged without adding. Here is the docstring snippets.

Added missing docstring for inner product.

---

WORKSPACE
release/setup.py
requirements.txt
tensorflow_quantum/core/ops/batch_util.py
tensorflow_quantum/core/ops/batch_util_test.py
tensorflow_quantum/core/ops/cirq_ops.py
tensorflow_quantum/core/ops/cirq_ops_test.py

After this goes in we should be ready for our 0.4.0 release.

Bump cirq to 0.9.0.

---

release/setup.py
tensorflow_quantum/__init__.py

Bump the working version of TFQ to 0.5.0.

Bump working version to 0.5.

---

tensorflow_quantum/core/__init__.py
tensorflow_quantum/core/ops/__init__.py
tensorflow_quantum/core/ops/tfq_utility_ops.py
tensorflow_quantum/core/ops/tfq_utility_ops_test.py
tensorflow_quantum/python/layers/circuit_construction/elementary.py
tensorflow_quantum/python/layers/circuit_construction/elementary_test.py

Add docs for append_circuit op

---

tensorflow_quantum/core/src/util_qsim.h
tensorflow_quantum/core/src/util_qsim_test.cc

remove some error messages due to sign/unsigned comparisons

---

docs/tutorials/quantum_data.ipynb

Headers rendered incorrectly when staging the tutorial. Forgot to add extra `#` symbol.

Fixed header rendering in quantum_data tutorial.

---

tensorflow_quantum/python/util.py
tensorflow_quantum/python/util_test.py

Updated error messaging for unsupported gates.

---

configure.sh
docs/_index.yaml

Add in two cards to the latest blog posts. Should I put these at the beginning or the end @lamberta ?

Add latest TF blog posts as landing cards on the site.

---

tensorflow_quantum/core/src/circuit_parser_qsim.cc
tensorflow_quantum/core/src/circuit_parser_qsim_test.cc

Almost done on #422 . This PR adds support for the `control_qubits` and `control_values` fields in the parsing layer for all of our gates. The last PR in this chain should be to just implement gates with `controlled_by` in our python tests and fix any last errors that pop up.

Added multi qubit support to circuit_parser_qsim.

---

.github/workflows/ci.yaml
tensorflow_quantum/core/ops/tfq_ps_util_ops_test.py

Moved the CI linter to use the same version we do locally. Amazed this managed to keep working as long as it did.

Fix CI installing latest version of pylint.

---

tensorflow_quantum/python/differentiators/adjoint.py
tensorflow_quantum/python/differentiators/linear_combination.py
tensorflow_quantum/python/differentiators/parameter_shift.py

Fix diff docstrings.

---

tensorflow_quantum/python/util.py
tensorflow_quantum/python/util_test.py

Updated `tensorflow_quantum.python.utils.py` with improved docstring consistency (e.g., kept language format consistent, updated a couple of typos, and added information about error raising), and input validation for some methods.

Update TFQ Python utils with input validation and docstring consistency

---

.github/workflows/ci.yaml
.github/workflows/cirq_compatibility.yaml
scripts/ci_validate_tutorials.sh

Also tweaks nbconvert version for new pip rules.

Upgrade CI to Py38.

---

tensorflow_quantum/core/ops/circuit_execution_ops_test.py
tensorflow_quantum/core/ops/tfq_utility_ops_test.py
tensorflow_quantum/python/util.py
tensorflow_quantum/python/util_test.py

Adds the ability for `random_***_circuit` and batch related methods to return circuits that contain channels.
Enables noisy tests on util ops.

[Noise] Adds noisy versions of util circuit functions.

---

tensorflow_quantum/core/ops/math_ops/inner_product_op_test.py
tensorflow_quantum/core/ops/tfq_adj_grad_op_test.py
tensorflow_quantum/core/ops/tfq_simulate_ops_test.py
tensorflow_quantum/core/ops/tfq_unitary_op_test.py
tensorflow_quantum/core/serialize/serializer.py
tensorflow_quantum/core/serialize/serializer_test.py
tensorflow_quantum/core/src/circuit_parser_qsim.cc

Adds error checking for all C++ ops that don't support noise.

[Noise] Adds errors for noiseless ops.

---

tensorflow_quantum/core/BUILD
tensorflow_quantum/core/ops/BUILD
tensorflow_quantum/core/ops/math_ops/BUILD
tensorflow_quantum/core/ops/noise/BUILD
tensorflow_quantum/core/proto/BUILD
tensorflow_quantum/core/serialize/BUILD
tensorflow_quantum/core/src/BUILD
tensorflow_quantum/datasets/BUILD
tensorflow_quantum/python/BUILD
tensorflow_quantum/python/differentiators/BUILD
tensorflow_quantum/python/layers/BUILD
tensorflow_quantum/python/layers/circuit_construction/BUILD
tensorflow_quantum/python/layers/circuit_executors/BUILD
tensorflow_quantum/python/layers/high_level/BUILD
tensorflow_quantum/python/optimizers/BUILD

This is required for google internal changes.

Add internal change

---

tensorflow_quantum/core/ops/tfq_ps_weights_from_symbols_op.cc
tensorflow_quantum/python/differentiators/BUILD
tensorflow_quantum/python/differentiators/differentiator.py
tensorflow_quantum/python/differentiators/gradient_test.py

Adds noisy ops to `gradient_test.py` Now all of our noisy ops should be supported by Differentiators that support sample based differentiation.

Added noisy ops to differentiators.

---

scripts/ci_validate_tutorials.sh
tensorflow_quantum/core/ops/noise/noisy_expectation_op.py

Adds missing docstring for noisy expectation op.

Added docstring for noisy expectation.

---

tensorflow_quantum/core/ops/BUILD
tensorflow_quantum/core/ops/tfq_adj_grad_op.cc
tensorflow_quantum/core/src/circuit_parser_qsim.cc

Some style fixes.  Also added build hints.

Fix CPP style

---

release/BUILD
scripts/import_test.py
tensorflow_quantum/python/layers/__init__.py
tensorflow_quantum/python/layers/high_level/BUILD
tensorflow_quantum/python/layers/high_level/__init__.py
tensorflow_quantum/python/layers/high_level/noisy_controlled_pqc.py
tensorflow_quantum/python/layers/high_level/noisy_controlled_pqc_test.py

Add NoisyControlledPQC layer.

---

docs/install.md
docs/tutorials/barren_plateaus.ipynb
docs/tutorials/gradients.ipynb
docs/tutorials/hello_many_worlds.ipynb
docs/tutorials/mnist.ipynb
docs/tutorials/qcnn.ipynb
docs/tutorials/quantum_data.ipynb

Final PR for upgrading to 0.5.0. Fixes #493 .

Upgrade all tutorials and install instructions.

---

qcnn_multiworker/Dockerfile
qcnn_multiworker/Makefile
qcnn_multiworker/README.md
qcnn_multiworker/common/qcnn_common.py
qcnn_multiworker/common/sa.yaml
qcnn_multiworker/inference/inference.yaml
qcnn_multiworker/inference/qcnn_inference.py
qcnn_multiworker/setup.sh
qcnn_multiworker/skaffold.yaml
qcnn_multiworker/training/apply_profiler_ports.sh
qcnn_multiworker/training/qcnn.py
qcnn_multiworker/training/qcnn.yaml
qcnn_multiworker/training/tensorboard.yaml

A tutorial for training a QCNN using multiple workers on top of Kubernetes and Google Cloud.
Replaces https://github.com/tensorflow/quantum/pull/557
@MichaelBroughton @lamberta

QCNN multi worker tutorial

---

release/setup.py
requirements.txt
tensorflow_quantum/core/serialize/serializer.py

Fixes #589 .
Fixes #423 .
This upgrade turned out to be super painless. Thought for sure we were going to have rounding / minor inconsistency issues.

Upgraded sympy to v1.8.

---

eq_gan/noise_suppression.ipynb
eq_gan/variational_qram.ipynb

Added two tutorials on eq-gan (see #325 for discussion)

eq-gan tutorials

---

tensorflow_quantum/core/ops/math_ops/tfq_inner_product_grad.cc
tensorflow_quantum/core/ops/noise/tfq_noisy_sampled_expectation.cc
tensorflow_quantum/core/src/circuit_parser_qsim_test.cc
tensorflow_quantum/core/src/util_qsim.h
tensorflow_quantum/core/src/util_qsim_test.cc
tensorflow_quantum/python/layers/high_level/controlled_pqc.py
tensorflow_quantum/python/layers/high_level/pqc.py

It's for the internal build system.

Fix internal build error

---

phase_classifier/phase_classification.ipynb

Hi, 
As discussed today, I would like to add my notebook for the TFQ whitepaper here so that there is a permanent place for people to check out the code. [Old Colab link](https://colab.research.google.com/drive/1kxUykovB0YMo0gBZd_r-8tJg4pzmO8Lc?usp=sharing).
It's not really readable right now, but I will try to clean this up over the weekend.
Do you need to review these as well?

Add notebook from whitepaper to repo

---

eq_gan/README.md

mention EQ-GAN tutorials in readme

---

docs/tutorials/barren_plateaus.ipynb
docs/tutorials/gradients.ipynb
docs/tutorials/hello_many_worlds.ipynb
docs/tutorials/mnist.ipynb
docs/tutorials/noise.ipynb
docs/tutorials/qcnn.ipynb
docs/tutorials/quantum_data.ipynb
docs/tutorials/quantum_reinforcement_learning.ipynb

Depending on the system configuration the tensorflow downgrade can break.
Reloading pkg_resources after the upgrade/downgrade fixes it.

importlib.reload(pkg_resources) for tensorflow.org

---

tensorflow_quantum/core/ops/math_ops/simulate_mps.py

Indicate that all ops use 1D non periodic simulation

Update MPS docs

---

docs/install.md
docs/tutorials/barren_plateaus.ipynb
docs/tutorials/gradients.ipynb
docs/tutorials/hello_many_worlds.ipynb
docs/tutorials/mnist.ipynb
docs/tutorials/noise.ipynb
docs/tutorials/qcnn.ipynb
docs/tutorials/quantum_data.ipynb
docs/tutorials/quantum_reinforcement_learning.ipynb
release/setup.py
requirements.txt
tensorflow_quantum/__init__.py

Upgrade version and install instructions for latest release.

---

binary_classifier/binary_classifier.ipynb
control/control.ipynb
eq_gan/noise_suppression.ipynb
eq_gan/variational_qram.ipynb
layerwise_learning/layerwise_learning.ipynb
metalearning_qaoa/metalearning_qaoa.ipynb
phase_classifier/phase_classification.ipynb
qaoa/qaoa.ipynb
qcnn_multiworker/Dockerfile
qgrnn_ising/qgrnn_ising.ipynb
quantum_embed/quantum_embed.ipynb
vqt_qmhl/vqt_qmhl.ipynb

Upgrades research notebooks for latest TFQ version.

Bump research branch to tf 2.7.0.

---

WORKSPACE
tensorflow_quantum/core/ops/noise/tfq_noisy_expectation.cc
tensorflow_quantum/core/ops/noise/tfq_noisy_sampled_expectation.cc
tensorflow_quantum/core/ops/noise/tfq_noisy_samples.cc

Pins to latest version (0.13.3).

Upgrade qsim version.

---

.github/problem-matchers/clang-format.json
.github/workflows/ci-build-checks.yaml
.github/workflows/ci-file-checks.yaml
.github/workflows/ci-nightly-build-test.yaml
.github/workflows/ci-nightly-cirq-test.yaml

There are no functional changes in this PR in terms of what checks are performed; everything concerns either
- bugs in the workflows that didn't become apparent until they were merged
- minor improvements for better error catching and reporting
- changes for style consistency across the files

Fix bugs & improve new CI workflows

---

.github/workflows/ci-build-checks.yaml
.github/workflows/ci-nightly-build-test.yaml
.github/workflows/ci-nightly-cirq-test.yaml

Ubuntu 20.04 is no longer available.

Replace Ubuntu 20.04 runners with 22.04
