docs/tutorials/barren_plateaus.ipynb
docs/tutorials/gradients.ipynb
docs/tutorials/hello_many_worlds.ipynb
docs/tutorials/mnist.ipynb
docs/tutorials/qcnn.ipynb

Remove the recommendation to restart the notebook. This doesn't seem necessary, and cause confusion:
If I  restart the notebook after running `%tensorflow_version`, and then continue where I left off, then I'm back to tensorflow 1.15, which gives some unclear errror: `NotFoundError: /usr/lib/python3/dist-packages/tensorflow_quantum/core/ops/_tfq_simulate_ops.so: cannot open shared object file: No such file or directory`

no-restart

---

tensorflow_quantum/core/qsim/BUILD
tensorflow_quantum/core/qsim/util.cc
tensorflow_quantum/core/qsim/util.h
tensorflow_quantum/core/qsim/util_test.cc

Added the ability to sample from state vectors in qsim. This is the first step in solving #144 .
Next step is to make an op around this. I put the functionality in `util.cc` since it is pretty hard for us to test `state_space` at the moment.
@zaqqwerty if you are going to get around to testing `state_space` soon do you think you could move this functionality over to `state_space` or would you rather we wait to put this in until we have some better testing on `state_space` ?

Added ability to sample from state vector in qsim.

---

tensorflow_quantum/core/ops/BUILD

Windows builds were flaking because they were unable to see the `M_PI` symbol. This will add the `_USE_MATH_DEFINES` flag into our builds which should hopefully fix the issue.

Added flag to enable _USE_MATH_DEFINES on windows

---

release/setup.py
requirements.txt
tensorflow_quantum/core/ops/batch_util.py

Convert from using multiprocessing to using the pathos library. Windows was having trouble pickling things for multiprocessing in #160 . Pathos seems to be a more robust alternative, but it is a little slower. I'm not super worried about the performance hit here, since if you are choosing to not use the C++ simulators you must have a good reason to be willing to forgo performance already.

Change from multiprocessing to pathos for windows compatability.

---

tensorflow_quantum/core/ops/parse_context.cc
tensorflow_quantum/core/ops/tfq_circuit_append_op.cc
tensorflow_quantum/core/ops/tfq_ps_decompose_op.cc
tensorflow_quantum/core/ops/tfq_ps_symbol_replace_op.cc
tensorflow_quantum/core/ops/tfq_ps_weights_from_symbols_op.cc

Cleaned up util ops and ps_util ops:
1. when dealing with tensor data apparently it's better to use `tensorflow::tstring` since it is more portable and such.
2. Added a few missing `OP_REQUIRES_OK`
3. Added shape outputs.

Some small util ops cleanup.

---

tensorflow_quantum/core/qsim/state_space.cc

Discussions were going on here https://github.com/quantumlib/qsim/pull/63 that led me to want to fix the biasing from just padding with the last sample to padding with the most likely bitstring sample. Seeing a few more bitstrings of the most likely outcome is much better than seeing a few more bitstrings that might have zero possible outcome.

Fixed bias in sample.

---

tensorflow_quantum/core/qsim/state_space.cc

We mixed up the ordering here, we did the check on the array entry before the bounds check. It should've been the other way around.

Fixed small oob error in sampling.

---

tensorflow_quantum/core/ops/tfq_simulate_state_op.cc

State was telling the shapeinference context that it's output shape was [batch, n_symbols] which is not correct, the shape is [batch, unknonwn dependent on input] I've updated the `set_output` to reflect this.

Fixed state op shapeinference shaping.

---

docs/install.md

Now that 2.2rc2 is on it's way and has introduced some upgrades that break us (`tensorflow::tstring` and bazel 2.0.0 among other things) we should indicate that we currently don't support the latest tensorflow until we have #181 go in and upgrade our nightly build pipelines.

Update install instructions

---

metalearning_qaoa/metalearning_qaoa.ipynb

There were some surprising typos, which I have now corrected.  Resolves #191.

Corrected metalearning example

---

docs/_index.yaml

Removes the Quantum supremacy blog post to keep 4-up

Add Dev Summit talk to landing page

---

requirements.txt

Looks like cirq didn't pin a version on their google-api-python-client and an update might have broken our CI. Investigating fix.

Pinned version of google-api-client.

---

tensorflow_quantum/core/ops/tfq_calculate_unitary_op.cc

Our nightly builds failed on windows recently with a narrowing conversion error. This PR is an attempted fix. Fixes #217

Fix windows compiler warnings.

---

release/setup.py

Cirq 0.8 currently breaks us. Fixing `setup.py` to hard pin to 0.7. Let me know if I've missed anything

Fixed Cirq version problems.

---

tensorflow_quantum/python/util_test.py

Fix cirq.unitary(np.exp(-1j * op))

---

tensorflow_quantum/core/ops/parse_context.cc

Cleaned up the `parse_context.cc` file. 
1. Added parallelization to the remaining parsing operations.
2. Moved off of deprecated `TransformRangeConcurrently` in favor of `ParallelFor`.
@jaeyoo or @philiptmassey do either of you have any idea on roughly how many cpu cycles we estimate parsing a single protobuf takes ?

Parallelized parsing operations.

---

release/setup.py
requirements.txt
tensorflow_quantum/core/ops/batch_util.py

Because `pathos` is just a wrapper of `multiprocessing`, we decided rolling back to `multiprocessing` by removing `pathos`.

Rollback pathos

---

tensorflow_quantum/core/ops/tfq_simulate_expectation_op.cc
tensorflow_quantum/core/src/circuit_parser_qsim.cc
tensorflow_quantum/core/src/util_qsim.h

Switched `tfq_simulate_expectation` over to depending on OSS qsim. Once we get this merged this will just leave
`tfq_simualte_sampled_expectation` and `tfq_calculate_unitary` left to do. This covers step 5 in #263 .

tfq_simulate_state uses OSS qsim.

---

tensorflow_quantum/core/src/circuit_parser_qsim.cc
tensorflow_quantum/core/src/circuit_parser_qsim.h
tensorflow_quantum/core/src/circuit_parser_qsim_test.cc

Porting over ZBasis conversion code from `circuit_parser` to `circuit_parser_qsim` in the ongoing effort here: #263 . This brings us one step closer to getting tfq_sampled_expectation onto OSS qsim too.

Ported Z basis parsing to OSS qsim.

---

tensorflow_quantum/core/ops/parse_context.cc

We Accidentally merged this in where we made potentially parallel access to the underlying hash_set. Easy fix :), note that the other change we made for parallel parsing of the PauliSums (which looks extremely similar) is not a concern since we don't have any potential for overlapping writes during the datasets "underlying expansion" moments.

Parse safety

---

tensorflow_quantum/core/ops/circuit_execution_ops_test.py
tensorflow_quantum/core/ops/tfq_simulate_state_op.cc

Noticed that there are certain cases where parallelizing over wavefunctions vs parallelizing over batches have their benefits. TL;DR Circuit smaller than 26 qubits can parallelize over the batch. Circuits larger than 26 qubits should parallelize over wavefunctions and process the batch serially. 
More specifically:
If the circuits are less than ~26 qubits , most machines (https://cloud.google.com/compute/docs/machine-types#e2_machine_types) should have enough memory to simulate circuits entirely isolated in their own threads. This is nice because we can assign large workloads to each thread without having to worry about memory or whether or not the threads have enough work to do.
If the circuits are more than 26 qubits we then run the risk of this O(num_threads * size of state vector) …

Smarter parallelization of state op

---

tensorflow_quantum/core/ops/tfq_simulate_state_op.cc

Windows nightly builds appear to have failed. Hoping this will fix things. It complained of having to use Eigen::Index and long. Perhaps if we don't specify any specific type it will default to some common ground. Maybe `ptrdiff_t` ?

Removed third template arg in simulate_state.

---

tensorflow_quantum/core/ops/tfq_simulate_expectation_op.cc
tensorflow_quantum/core/ops/tfq_simulate_sampled_expectation_op.cc
tensorflow_quantum/core/ops/tfq_simulate_samples_op.cc
tensorflow_quantum/core/ops/tfq_simulate_state_op.cc

Seems like more and more people are using TFQ for single circuit experiments. It makes sense to have us use all cores in that case.

Use all cores when batch_size==1.

---

release/setup.py

Adds the ability to do `python3 -m pip install tensorflow-quantum[extras]` which will also include a known-working version of `tf` version to depend on if the user doesn't have a nightly installed.

Added tf 2.1.0 under extras.

---

WORKSPACE
configure.sh
release/build_all_wheels.sh
release/setup.py
requirements.txt
scripts/build_pip_package_test.sh
scripts/ci_install.sh
scripts/test_all.sh
tensorflow_quantum/python/differentiators/gradient_test.py

When a new relaease is cut, we will need to upgrade the version in all of the tutorials and docs too. Just want to confirm with @yashk2810 that we won't upgrade anything in the `docs/` folder (including tutorials) until we cut a new pip release, then we will upgrade all the 2.1.0 -> 2.3.0 in there.

Updated nightly to tf 2.3.0 and bazel 3.1.0.

---

tensorflow_quantum/core/src/BUILD
tensorflow_quantum/core/src/adj_util.cc
tensorflow_quantum/core/src/adj_util.h
tensorflow_quantum/core/src/adj_util_test.cc

Added the `GradientOfGate` struct and corresponding circuit analysis logic to be used by the adjoint method. This marks all the code that needs adding in the `src` directory. From here out it should be writing the C++ op code as well as the rest of the python implementation. Progressing on #256 .

Adjoint 3/n: Adding parsing functionality for adjoint needs.

---

tensorflow_quantum/core/ops/BUILD
tensorflow_quantum/core/ops/parse_context.cc
tensorflow_quantum/core/ops/parse_context.h
tensorflow_quantum/core/ops/tfq_adj_grad_op.cc
tensorflow_quantum/core/ops/tfq_adj_grad_op.py
tensorflow_quantum/core/ops/tfq_adj_grad_op_test.py
tensorflow_quantum/core/src/circuit_parser_qsim.cc

Adds a basic functioning op for the adjoint gradient. I'm thinking that we should NOT expose this op to the user and instead force them to make use of the differentiatiors interface with an appropriately linked op, that is why I haven't made any modifications to the `__init__.py` files. My thinking behind this is that if a user wanted to call into this op they could just as easily do an appropriate `with tf.GradientTape() ...` style statement that sticks more closely to the expected TF logic for getting out gradients instead of `tfq.adj_grad(...)`.
What do @zaqqwerty and @jaeyoo think ?
Yet more progress on #256 . One or two more PRs should do it.

Adjoint 4/n: Added basic functioning op.

---

tensorflow_quantum/core/ops/BUILD
tensorflow_quantum/core/ops/circuit_execution_ops.py
tensorflow_quantum/python/quantum_context.py

In the future if we want to link other ops into the same GLOBAL_OP_LOCK instance we will need it in a more global location than `circuit_executions_ops.py`. This move fixes this. Related: #364

Move GLOBAL_OP_LOCK to quantum_context.

---

tensorflow_quantum/core/ops/tfq_adj_grad_op.cc
tensorflow_quantum/core/ops/tfq_simulate_expectation_op.cc
tensorflow_quantum/core/ops/tfq_simulate_sampled_expectation_op.cc

Modified Adjoint method to do Full fusing in the forward pass instead of the same (potentially slower) partial fusing that we need to do in the backward pass.
Also changed some `>=` to `>` that were accidentally triggering re-allocations when they weren't needed.

Speed up adjoint.

---

tensorflow_quantum/core/ops/BUILD
tensorflow_quantum/core/ops/tfq_calculate_unitary_op.cc

This took a lot longer than expected.
Moved `tfq.calculate_unitary` off of old qsim. I opted to not provide a `ComputeSmall` and `ComputeLarge` option in this case, since memory requirements (most times) would put it in the `ComputeLarge` category.
This will get point number 7 on #263 .

Moved unitary onto new qsim.

---

tensorflow_quantum/core/src/program_resolution.cc
tensorflow_quantum/core/src/program_resolution.h
tensorflow_quantum/core/src/program_resolution_test.cc

In order to support ops like `tfq.math.overlap` or any other program to program based operations, we will need a way to parse them in pairs and ensure they operate on the same qubits etc. This PR adds that functionality.

Parsing functionality for program-program.

---

WORKSPACE

With the removal of the last of our custom qsim code, it seems the Eigen library is now unused.  xref #323.

removed unused eigen library

---

configure.sh

Just a small quality of life improvement to allow us to write statements like 
`bazel test ...` without having to worry about adding in the long abi flag everytime.

Add explicit use_cxx11_abi=0 to configuration.

---

tensorflow_quantum/core/ops/tfq_ps_decompose_op.cc
tensorflow_quantum/core/ops/tfq_simulate_ops_test.py
tensorflow_quantum/core/serialize/serializer.py
tensorflow_quantum/core/serialize/serializer_test.py

Addresses step 2 in #422 .
The final step is to link these gates into the new qsim simulator. Right now most of the C++ code still ignore `control_qubits` and `control_values` proto fields.
With the help of the `DelayedAssignmentGate` this change adds the `control_qubits` and `control_values` field to every gates [args](https://github.com/quantumlib/Cirq/blob/master/cirq/google/api/v2/program.proto#L110) field. Updates all previous tests to use controlled operations as well and added a test for invalid `control_qubits`. Plz review closely, I'm always a little concerned when touching code in `serializer.py` since it's used so widely.

Serialize multiqubit

---

docs/tutorials/quantum_data.ipynb

In fashion-MNIST dataset level 0 = T-shirt/top and level 3 = dress but mistakenly they mention level 0 = shirt (actually, shirt = level 6), this text doesn't match with below code. So, I change this text according to the code.
After modification it looks -
**Reference-** 
https://github.com/zalandoresearch/fashion-mnist#labels

Misclassified fashion-MNIST dataset image level.

---

docs/tutorials/quantum_data.ipynb

Despite my best efforts the quantum_data tutorial flakes around 1 in every 8 runs. The version that is live happened to be one such flake. I ran locally and saved outputs and flagged the docs infra to not run the flaky cells.

Fixed outputs for quantum_data.

---

tensorflow_quantum/core/src/program_resolution.cc
tensorflow_quantum/core/src/program_resolution_test.cc

This is another step on the journey to closing #422 . Now we can resolve qubit ids to their integer values correctly in the `ResolveQubitIDs` functions in the controlled gate case. Next step is to implement changes in `circuit_parser_qsim.cc`.
I also cleaned up the tests so that they are much smaller and each one targets certain behavior more explicitly.

Adds support for resolving qubit ids in controlled gates

---

configure.sh

related to this issue and PR: 
https://github.com/tensorflow/custom-op/issues/74
https://github.com/tensorflow/custom-op/pull/79/files
It can affect this issue, even if cpu only custom ops are compiled:
https://github.com/tensorflow/tensorflow/issues/43022
```
2020-09-07 15:46:38.915193: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-09-07 15:46:38.915211: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-07 15:46:40.468711: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-09-07 …
```

Fix the tensorflow package naming in configure.sh

---

docs/tutorials/hello_many_worlds.ipynb

In part 2 of the hello many worlds tutorial we used some paulisum operations that were defined on qubits defined in part 1. This changes things so that the paulisums defined in part 2 use qubits from part 2. Fixes #467

Removes use of old qubits

---

WORKSPACE
configure.sh
release/setup.py
requirements.txt

Almost as painless as 2.3.0 -> 2.3.1 only instead of a micro version we jumped a minor version. This is the first half of addressing #460 . Interestingly I had to use 2.4.1 since 2.4.0 didn't appear to work after build+install. The second half will come in the form of an update to the install + docs when we cut an official release.
I've also modified the configure script since CPU and GPU are now all inside of the package `tensorflow` and I'm not 100% sure why we were making sure to distinguish between `tensorflow-cpu` and `tensorflow-gpu` @jaeyoo do you have any ideas ?
Note: Once this goes in we will need to update internal builds for nightly.

Upgrade nightly builds to tf 2.4.1.

---

tensorflow_quantum/core/ops/tfq_utility_ops_test.py
tensorflow_quantum/python/util.py
tensorflow_quantum/python/util_test.py

Add functions to approximately compare parameterized gates in the TFQ gate set.
Supersedes #462 .  In this PR, full support for ControlledGates is added.

Custom gate_approx_eq

---

scripts/import_test.py
tensorflow_quantum/core/serialize/serializer.py
tensorflow_quantum/core/serialize/serializer_test.py
tensorflow_quantum/python/__init__.py
tensorflow_quantum/python/util.py
tensorflow_quantum/python/util_test.py

Adds serialization support for the depolarizing channel. First step in getting #250 finished. Once we have serialization support in place, hopefully we can upgrade our qsim dependancy and have https://github.com/quantumlib/qsim/issues/288 resolved so we can immediately start plumbing the support for channels.
CC: @balopat , @95-martin-orion

Add support for cirq.DepolarizingChannel in serialize_circuit.

---

docs/install.md

Updates the build from source instructions for TFQ in light of #482 . When we can an official release we will still have to remember to update the rest.
cc @balopat

Update build from source instructions.

---

tensorflow_quantum/core/serialize/serializer_test.py

Removes a call to a private function that changed in cirq since 0.9.1.

fix resolve_parameter call ahead of cirq release

---

.github/workflows/cirq_compatibility.yaml
requirements.txt
tensorflow_quantum/core/serialize/serializer_test.py

Now we test against Cirq master and should be able to flag breakages as they happen.
Related: https://github.com/quantumlib/Cirq/issues/3828

Add nightly consistency checks for Cirq

---

WORKSPACE
tensorflow_quantum/core/ops/tfq_calculate_unitary_op.cc

Pretty straightforward upgrade, should enable #487 to merge in. Won't be our last qsim upgrade in the next little while since we do still need support on https://github.com/quantumlib/qsim/issues/288 in a release.
Note: qsim swapped indexing for unitaryspace so that's why we make the index change.

Upgrade qsim to 0.8.0.

---

tensorflow_quantum/python/differentiators/differentiator.py

Adds an empty check to the `tf.cond` that checks if the `symbol_names` tensor is empty to avoid accidentally computing lots of circuit info, only to not use any of it.

Add symbol_names empty check to diffs

---

tensorflow_quantum/python/differentiators/gradient_test.py

With our fast C++ noisy ops coming up and our no longer having a very large need for pure python backends, I figured we might as well remove the `cirq.DensityMatrix` instances from our gradient tests.

Removed DM from gradient_test.py

---

tensorflow_quantum/core/ops/math_ops/inner_product_op.py

In the true case this would return type `tf.float32` and in the false case we would get `tf.complex64` updated so it's `tf.complex64` everywhere.

fix type mismatch in ip op.

---

docs/tutorials/mnist.ipynb

I assume 1.4 comes after 1.3 numerically and **not** 1.3 again. 😀

Updated mnist.ipynb Typo in section header

---

release/BUILD
scripts/import_test.py
tensorflow_quantum/core/ops/noise/BUILD
tensorflow_quantum/core/ops/noise/__init__.py
tensorflow_quantum/core/ops/noise/noisy_sampled_expectation_op.py
tensorflow_quantum/core/ops/noise/noisy_sampled_expectation_op_test.py
tensorflow_quantum/core/ops/noise/tfq_noisy_sampled_expectation.cc
tensorflow_quantum/core/src/util_qsim.h
tensorflow_quantum/core/src/util_qsim_test.cc
tensorflow_quantum/python/differentiators/linear_combination_test.py
tensorflow_quantum/python/layers/circuit_executors/sampled_expectation_test.py

Adds support for noisy sample based expectation. Note it's basically identical to the analytical case but we instead call into `ComputeSampledExpectationQsim`. Since we are only ever taking 1 shot per circuit realization I had to modify this function to no longer have a fixed seed.

Add tfq.noise.sampled_expectation.

---

tensorflow_quantum/core/ops/noise/tfq_noisy_expectation.cc
tensorflow_quantum/core/ops/noise/tfq_noisy_sampled_expectation.cc
tensorflow_quantum/core/ops/noise/tfq_noisy_samples.cc
tensorflow_quantum/core/ops/tfq_simulate_sampled_expectation_op.cc
tensorflow_quantum/core/ops/tfq_simulate_samples_op.cc
tensorflow_quantum/core/src/util_qsim.h
tensorflow_quantum/core/src/util_qsim_test.cc

Over time I was noticing that the randomness sources in our parallel ops weren't behaving very well. This change removes all of the old either constant or not completely thread safe sources of randomness and replaces them with proper random sequence generators from the standard library.

Improved randomness sources in parallel ops.

---

tensorflow_quantum/core/ops/noise/noisy_samples_op_test.py
tensorflow_quantum/python/differentiators/linear_combination.py
tensorflow_quantum/python/differentiators/linear_combination_test.py
tensorflow_quantum/python/differentiators/parameter_shift.py

For after #532.  During implementation of that PR, I discovered a more efficient way to represent the gradient structure: separating the old `batch_mapper` into a weights tensor and an index tensor.  In the updated tests in this PR, it can be seen that this eliminates the zero padding previously required.

Gradient circuits 4/n: update LinearCombination

---

tensorflow_quantum/core/ops/cirq_ops.py
tensorflow_quantum/python/layers/circuit_executors/BUILD
tensorflow_quantum/python/layers/circuit_executors/sampled_expectation.py
tensorflow_quantum/python/layers/circuit_executors/sampled_expectation_test.py

Modifies `SampledExpectation` to support noisy and noiseless backends. This also improves on #504 by giving more intuitive meaning to the `backend` parameter. I wasn't able to modify the differentiator default behavior because: https://florimond.dev/blog/articles/2018/08/python-mutable-defaults-are-the-source-of-all-evil/  and we must create a new instance for each layer. I remember now why we didn't do this to begin with.
This change still supports legacy calls into the layer with `backend=None` in the same fashion as the old API, so it is not a breaking change. Please review closely.
cc: @lockwo .

Added noise support to SampledExpectation.

---

tensorflow_quantum/python/differentiators/linear_combination_test.py
tensorflow_quantum/python/differentiators/parameter_shift_test.py

The tolerances on these tests was a little too tight on my local machine so reduced them down.

Loosen differentiator test tols.

---

tensorflow_quantum/core/ops/noise/tfq_noisy_samples.cc
tensorflow_quantum/python/layers/circuit_executors/BUILD
tensorflow_quantum/python/layers/circuit_executors/sample.py
tensorflow_quantum/python/layers/circuit_executors/sample_test.py

Like #540 this PR adds the noisy backend to the `Sample` layer and also helps with #504 . These tests also helped me find an issue on our C++ op where if we set n_samples = 1 and n_circuits < n_threads we might encounter race conditions on writes, so there is also a very small tweak to the .cc file as well.

Added noisy backend to sample layer.

---

tensorflow_quantum/python/layers/circuit_executors/BUILD
tensorflow_quantum/python/layers/circuit_executors/expectation.py
tensorflow_quantum/python/layers/circuit_executors/expectation_test.py
tensorflow_quantum/python/layers/circuit_executors/sampled_expectation.py

Redefines `backend` behavior for `tfq.layers.Expectation`. `noisy` requires that a value for `repetitions` be provided at a call time. `noiseless` (the default) behaves just like None , while keeping backwards compatability with None so that we can improve on #504 .

Added noisy backend to Expectation layer.

---

tensorflow_quantum/python/layers/high_level/controlled_pqc.py
tensorflow_quantum/python/layers/high_level/controlled_pqc_test.py
tensorflow_quantum/python/layers/high_level/pqc.py
tensorflow_quantum/python/layers/high_level/pqc_test.py

Fixes #504 . Sets the default backend to `'noiseless'` for our existing PQC layers and adds errors that will reffer users to the incoming `Noisy***PQC` layers. This comes after the discussions in the weekly sync that it unlike the Expectation and SampledExpectation layers fitting the notion of `noisy` vs `noiseless` into the PQC layers isn't as clean so we will break them up into two seperate layers.

Update ***PQC layers to use new backend conventions.

---

release/BUILD
scripts/import_test.py
tensorflow_quantum/python/layers/__init__.py
tensorflow_quantum/python/layers/high_level/BUILD
tensorflow_quantum/python/layers/high_level/__init__.py
tensorflow_quantum/python/layers/high_level/noisy_pqc.py
tensorflow_quantum/python/layers/high_level/noisy_pqc_test.py

Adds the `NoisyPQC` layer a variant of `PQC` for noisy simulation only. Note that in this layer we do not support exotic backends like `PQC` and always require the user to specify a value for repetitions and whether they want sampled based approaches or not.

Add NoisyPQC layer.

---

tensorflow_quantum/core/ops/batch_util.py
tensorflow_quantum/core/ops/batch_util_test.py

Removes parallel calls into python simulators when sampling. Also fixes datatype outputs to match that of that high speed C++ ops (int8).

Remove parallelization in batch sample.

---

qcnn_multiworker/Dockerfile

Pinning dependency versions to make the tutorial more reproducible. Also explicitly pinning `google-cloud-core` version to temporarily bypass the issue mentioned in https://github.com/tensorflow/quantum/pull/498#issuecomment-851761745.
Without this fix, training fails while trying to look for `OpenSSL` in the package `google-auth`.

QCNN multiworker: pin dependencies to exact versions in Dockerfile

---

release/setup.py

Fixes #572 . Once we get this merged, we can experiment with the nightly release and if things look good we can cut a point release of 0.5.1 with this cherry picked on.

Removed fixed grpcio version.

---

scripts/build_docs.py
tensorflow_quantum/core/ops/math_ops/fidelity_op.py
tensorflow_quantum/core/ops/math_ops/inner_product_op.py

Fixes #577 . Also removes accidental renderings of op modules like [this one](https://www.tensorflow.org/quantum/api_docs/python/tfq/math/fidelity_op)

Cleaned up latex and docs rendering.

---

docs/_index.yaml

Added new link cards on the landing page. First row: a link to the distributed blog post.
Second row: a link to the research branch of the github.

Updated tensorflow.org/quantum landing cards.

---

tensorflow_quantum/core/ops/math_ops/fidelity_op.py
tensorflow_quantum/core/ops/math_ops/fidelity_op_test.py
tensorflow_quantum/core/ops/math_ops/tfq_inner_product_grad.cc

When calling:
```python3
tf.GradientTape() as tape:
tape.gradient(some fid op)
```
The fid op would backprop through to the inner_product op who's gradients are complex64 (as they should be). However this can be unintuitive to the user who might not be expecting this. This PR ensures that the gradient of the fidelity op remains f32 at all times. It does not change the types of the inner_product grad which would still remain complex64.

Ensure gradient of tf.math.fidelity remains float32 when autographed.

---

quantum_embed/quantum_embed.ipynb
quantum_embed/quantum_embed.py
quantum_embed/quantum_embed_test.py

This PR tries to re-create a series of paper by Schuld et al. regarding the universality of quantum embeddings

Quantum embedding

---

third_party/tf/auditwheel

The recent change in auditwheel shows different file name for the `policy.json`. Let's use the right json file for manylinux as located at:
https://github.com/pypa/auditwheel/blob/main/src/auditwheel/policy/manylinux-policy.json

Fix auditwheel script

---

release/BUILD
scripts/build_docs.py
scripts/import_test.py
tensorflow_quantum/python/optimizers/BUILD
tensorflow_quantum/python/optimizers/__init__.py
tensorflow_quantum/python/optimizers/rotosolve_minimizer_test.py
tensorflow_quantum/python/optimizers/spsa_minimizer.py
tensorflow_quantum/python/optimizers/spsa_minimizer_test.py

SPSA is a common optimizer that plays a prominent role in many quantum optimization procedures. It already exists in other popular packages such as [qiskit](https://qiskit.org/documentation/stubs/qiskit.algorithms.optimizers.SPSA.html#qiskit.algorithms.optimizers.SPSA). Although there are external implementations (e.g. noisyopt), providing a built in version offers a number of advantages (not the least of which is ease of use). The code is short and not complex (and shares the same format as the rotosolve optimizer). I would also like to answer two question which may arise (and I had when implementing):
Why SPSA? 
There are a number of black box optimization algorithms; however, SPSA is probably one of most common in the field of quantum optimization. It is a go to optimizer for VQE (see …

Add SPSA optimizer

---

docs/tutorials/barren_plateaus.ipynb

Since we only have data points at x=4, 6, 8, 10, and 12, it is better to get rid of the odd numbered ticks to avoid confusion.

constrain xticks in two plt figures

---

tensorflow_quantum/python/optimizers/spsa_minimizer.py

One word typo fix for the example provided in SPSA docs

Typo in example for SPSA

---

tensorflow_quantum/core/ops/cirq_ops.py

This allows for more efficient implementations of running a batch (for example parallelization).
run_batch delegates to run_sweep in the default implementation, so this should be drop-in equivalent, AIUI.

Use run_batch in cirq.Sampler

---

tensorflow_quantum/python/layers/circuit_executors/sample.py

The CNOT gate in the first example in tfq.layers.Sample has only 1 input (but needs 2)
This just adds the other input so it matches the diagram

Fixing small documentation bug in tfq.layers.Sample

---

docs/tutorials/mnist.ipynb

Fixes build failure by specifying the `x` and `y` axis in `sns.barplot`.
From the API docs:
```
seaborn.barplot(data=None, *, x=None, y=None,...)
```
(reference: https://seaborn.pydata.org/generated/seaborn.barplot.html) 
LMKWYT @MichaelBroughton @MarkDaoust

Documentation: Fix TF Quantum MNIST by adding arg names in Seaborn barplot

---

docs/tutorials/barren_plateaus.ipynb
docs/tutorials/gradients.ipynb
docs/tutorials/hello_many_worlds.ipynb
docs/tutorials/mnist.ipynb
docs/tutorials/noise.ipynb
docs/tutorials/qcnn.ipynb
docs/tutorials/quantum_data.ipynb
docs/tutorials/quantum_reinforcement_learning.ipynb
release/setup.py

Moves working version to 0.7.4. Also upgrades install version in notebooks.

Bump version to 0.7.4.

---

.github/workflows/ci.yaml
.github/workflows/cirq_compatibility.yaml

The aim of this PR is to stop the current CI workflow failures in `ci.yaml` and `cirq_compatibility.yaml` (both in `.github/workflows/`).
In the case of the failure in `ci.yaml`, the change is only a stopgap measure: it disables the address sanitizer tests.  The failures happen when the workflow runners are updated from Ubuntu 16.04 to 20.04; this update is necessary because GitHub no longer offers the Ubuntu 16 runners.
After spending a ridiculous amount of time testing various combinations of TensorFlow, TensorFlow Quantum, and compiler toolchains on a more recent Linux, my conclusion is that the ASAN failures stem from differences in the toolchains used to produce the copy of TensorFlow 2.15.0 we get from PyPI, and what we get under Ubuntu 20 when compiling TFQ on GitHub. This …

Minimum changes to make CI workflows work again

---

.github/workflows/cirq_compatibility.yaml
scripts/test_all.sh

This refactors the entire workflow. Improvements:
- Caches pip-downloaded Python packages
- Uses a Bazel setup action that caches Bazel installations
- Allows Bazel build artifacts to be downloaded – useful when debugging
- Adds a workflow_dispatch target to enable manual invocation of workflow
- Adds options to the workflow dispatch for controlling caching

Improve cirq_compatibility.yaml

---

third_party/tf/tf_configure.bzl

Bazel 6.5.0 complains about
```
(04:17:26) WARNING: ..../external/local_config_tf/BUILD:8216:8:
target 'libtensorflow_framework.so' is both a rule and a file;
please choose another name for the rule
(04:17:26) WARNING: ..../external/local_config_tf/BUILD:8226:8:
target 'test_log_pb2.py' is both a rule and a file;
please choose another name for the rule
```
(Note: I elided the long pathnames in the messages above by replacing them with '....'.) The warnings come from definitions in `third_party/tf/tf_configure.bzl` where the names of a couple of rules are `libtensorflow_framework.so` and `test_log_pb2.py`. Changing the names to `libtensorflow_framework_so` and `test_log_pb2_py` resolves the problem. Other names are possible, of course, but those seem like good choices in order to keep …

Fix warnings "target is both a rule and a file"

---

tensorflow_quantum/core/src/util_qsim_test.cc

`INSTANTIATE_TEST_CASE_P` is deprecated and produces compilation warnings. The replacement is `INSTANTIATE_TEST_SUITE_P`.

Replace deprecated INSTANTIATE_TEST_CASE_P

---

configure.sh

A number of harmless warnings during compilation come from third-party things pulled in by the TFQ build rules. They involve things like unused functions, unused variables, or some deprecated constructs. The best way to fix them would be in the original source code, but in some cases this is impossible; for example, we can't change what TensorFlow 2.15.0 needs. The second best way would be to add patch rules in TFQ to adjust the code or the build rules. I spent a couple of hours trying to figure out how to that for the copy of zlib included by bazel_rules, but due to my still-limited Bazel knowledge, I wasn't able to get the patching scheme working. So, for the time being, and in consideration of the harmless nature of the warnings, the approach taken here is to add compile-time per-file …

Add bazel flags to silence compiler warnings we can't do anything about

---

scripts/lint_all.sh

The `lint_all.sh` script invoked `pylint` with a couple of subdirectories, including `./examples`. However, that directory doesn't exist.
Apparently Pylint version 2.4.4 didn't complain about this, but later versions of Pylint do.

Remove reference to non-existent directory

---

requirements.txt

Yapf version 0.43.0 seems to be entirely compatible with the previously-used version 0.40.2. Running it recursively on the codebase produced no output.

Update yapf to version 0.43.0

---

.github/workflows/ci-build-checks.yaml
.github/workflows/ci-file-checks.yaml

This is the first PR in what will be several PRs to update and improve the CI checks workflows. This PR simply moves the lint & format checks to a new, separate workflow file (`ci-file-checks.yaml`) and renames `ci.yaml` to `ci-build-checks.yaml`. There are no functional changes, apart from adjusting the conditions of the build tests in `ci-build-checks.yaml` to not condition them on passing lint/format checks.
Lint/format checks are not a strictly necessary precondition to testing builds and doing unit tests, and running them in parallel affords a couple of advantages:
- Faster overall CI execution.
- Potential for more feedback. If a lint step fails, it doesn't necessarily mean that the code won't compile, and proceeding with the build tests gives devs as much feedback as possible. …

Move CI lint/format checks into separate file

---

tensorflow_quantum/python/layers/high_level/noisy_controlled_pqc_test.py

This fixes the incorrect `dict` being passed as an argument to the test function `test_controlled_pqc_simple_learn`, reported in issue #849.

Fix issue #849: incorrect argument passed to test function

---

.pylintrc
requirements.txt
scripts/lint_all.sh

This updates `requirements.txt` to use Pylint version 3.3.3 and also updates `.pylintrc` such that it's compatible with 3.3.3 yet does not raise any new warnings in the code base. The intention of this PR is to make only the minimal changes needed to use pylint 3.3.3.
The `.pylintrc` started life as the config file produced by pylint 3.3.3 with the `--generate-rcfile` option. I then compared it to the previous `.pylintrc` and adjusted the settings to match, followed by a long period of test-adjust-retest:
1. run `pylint` on the existing code base
2. look at the warnings, find the relevant flags & turn them off
3. if there are more warnings, go back to step 1
This `.pylintrc` file thus has a lot of pylint checkers commented out. We should systematically re-enable the checkers and fix the …

Update version of pylint to 3.3.3

---

release/setup.py

PyPI now supports a classifier term for quantum computing.

Add new Trove classifier term for quantum computing

---

.github/problem-matchers/README.md
.github/problem-matchers/pylint.json
.github/workflows/ci-file-checks.yaml

Vastly overhaul the CI workflow for file checks
This is a complete rewrite of the file checks portion of the CI workflow. It incorporates many new features and efficiency gains. It also serves as a framework for adding additional file linters/format checkers, such as for YAML, Markdown, shell scripts, and more.
Features:
- Serious use of caching of the Python installation and environment, so that repeated runs don't have to reinstall everything every time.
- Concurrency detection: if a new event such as a push to a PR branch comes in while a workflow is already executing, that workflow is cancelled and a new one restarted. (The existing workflow keeps the existing one running and starts a second one, which is almost never useful.)
- File-aware execution: the workflow tests which files …

Vastly overhaul the CI workflow for file checks

---

.github/workflows/ci-nightly-cirq-test.yaml
.github/workflows/cirq_compatibility.yaml

This updates has no behavioral changes. There is one minor bug fix: use `set -o pipefail` in a run action where a failure could have been masked by subsequent comments in a pipe.
The rest is all minor refactoring & updates:
- update the `setup-bazel` action to the latest version
- move the `on` workflow trigger definitions higher in the file
- add a `concurrency` section like we have in other workflows
- add type and default definitions to `workflow_dispatch` options
- rename the file to be more consistent with the other workflow names

Minor refactoring, cleanup, & updates to Cirq CI workflow

---

.github/workflows/ci-build-checks.yaml

This workflow compiles TFQ and runs test cases to verify things work after file changes are made by a PR or other event. It is a complete rewrite of the previous TFQ build & test checks CI workflow, and incorporates many new features and efficiency gains:
- Serious use of caching of the Python installation and environment, as well as the Bazel environment, so that repeated runs don't have to reinstall everything every time.
- File-aware execution: the workflow tests whether source files and build configuration files have been modified in a given event, and stops early if the event didn't affect such files.
- Compatibility with GitHub [merge queues](https://github.blog/news-insights/product-news/github-merge-queue-is-generally-available/).
- Concurrency detection: if a new event such as a …

Vastly overhaul the CI workflow for build checks

---

.github/workflows/ci-build-checks.yaml
.github/workflows/ci-file-checks.yaml

I keep forgetting this repo uses `master`, not `main`.

Fix main → master branch name

---

.github/problem-matchers/yamllint.json
.github/workflows/ci-file-checks.yaml

This adds a job to run `yamllint` on `*.{yaml,yml}` files in the repository. YAML files are currently found not only in the GitHub workflows directory; they're also in `docs/`, and we can imagine more YAML-based config files being added in the future.

Add YAML file check

---

.yamllint.yaml

Somehow, my previous PRs for adding yamllint did not include the `.yamllintrc` file. Here it is.

Add missing yamllint config file

---

.github/workflows/ci-nightly-cirq-test.yaml

Although the latest release of Cirq is compatible with NumPy 2, other
dependencies for TFQ are not, and this leads to failures at run-time.
For now, tell `pip` not to install NumPy 2.

Constrain numpy version to be less than 2.x

---

.github/workflows/ci-nightly-cirq-test.yaml

It turns out the pip `--pre` flag carries over to other packages that get installed as transitive dependencies. This can cause unexpected compatibility issues. We can avoid using `--pre` by switching to using `cirq~=1.0.dev`, which is more limited in its scope and gets us the latest dev version. Doing so ends up resolving issue #884.

Fix #884 by avoiding using `--pre` with pip install in nightly Cirq compatibility checks

---

.github/workflows/ci-build-checks.yaml
.github/workflows/ci-file-checks.yaml
.github/workflows/ci-nightly-build-test.yaml
.github/workflows/ci-nightly-cirq-test.yaml

This adds support for GitHub [merge queues](https://github.blog/news-insights/product-news/github-merge-queue-is-generally-available/). Merge queues help make sure a pull request is compatible with other changes ahead of it. It's being used in Quantumlib projects successfully.
This PR also adds missing copyright headers to the workflow files.

Support merge queues for CI workflows
